ALTER TABLE RULE_CONDITION_MAP ADD CONSTRAINT RULE_CONDITION_MAP_FK_1 FOREIGN KEY (CONDITION_ID) REFERENCES CONDITION (CONDITION_ID);
ALTER TABLE RULE_CONDITION_MAP ADD CONSTRAINT RULE_CONDITION_MAP_FK_2 FOREIGN KEY (RULE_ID) REFERENCES RULE (RULE_ID);

ALTER TABLE RULE_SET_CONF ADD CONSTRAINT RULE_SET_CONF_FK_1 FOREIGN KEY (RULE_SET_ID) REFERENCES RULE_SET (RULE_SET_ID);
ALTER TABLE RULE_SET_CONF ADD CONSTRAINT RULE_SET_CONF_FK_2 FOREIGN KEY (RULE_ID) REFERENCES RULE (RULE_ID);